name: CD

on:
  pull_request:
    branches: [ main, master ]
    types: [closed]

jobs:
  deploy:
    if : github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log deployment
      run: echo "Deployed!"