name: CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    #- name: Build (Optional step)
    #  run: npm run build

    # building the docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ vars.RELEASE_VERSION }}